# coding: utf8

from random import random, seed


# Hell yeah !
seed(42)

# Compute shader settings
RAY_COUNT = 128 * 16
RAY_GROUP_SIZE = 128

RAY_DIR_COUNT = 128
RAY_DIR_GROUP_SIZE = 64

# Ray batch 0
RAY_INIT_DX = -1.0
RAY_INIT_DY = -1.0
RAY_INIT_JITTER_OX = 0.0

RAY0_DATA_OX = [-0.9 + (i / RAY_COUNT) * 1.8 + random() * RAY_INIT_JITTER_OX for i in range(RAY_COUNT)]
RAY0_DATA_OY = [+0.3] * RAY_COUNT
RAY0_DATA_DX = [RAY_INIT_DX] * RAY_COUNT
RAY0_DATA_DY = [RAY_INIT_DY] * RAY_COUNT

#RAY0_DATA_OX = RAY0_DATA_OX[100:101]
#RAY0_DATA_OY = RAY0_DATA_OY[100:101]
#RAY0_DATA_DX = RAY0_DATA_DX[100:101]
#RAY0_DATA_DY = RAY0_DATA_DY[100:101]
#RAY_COUNT = len(RAY0_DATA_OX)
#RAY_GROUP_SIZE = 1

# World 0
#WORLD_INT_LINE_COUNT = 256
#WORLD_INT_X_JITTER = 0.0
#WORLD_INT_Y_JITTER = 0.005
#
#INTX_POINT_COUNT = WORLD_INT_LINE_COUNT + 1
#INT_X = [WORLD_INT_X_JITTER * random() + -1.0 + (i / WORLD_INT_LINE_COUNT) * 2.0 for i in range(INTX_POINT_COUNT)]
#INT_Y = [WORLD_INT_Y_JITTER * random() + -0.2 for i in range(INTX_POINT_COUNT)]
#WORLD_LINE_COUNT = WORLD_INT_LINE_COUNT

# World 1
#WORLD_INT_LINE_COUNT = 128
#WORLD_INT_X_JITTER = 0.0
#WORLD_INT_Y_JITTER = -0.5
#
#INTX_POINT_COUNT = WORLD_INT_LINE_COUNT + 1
#INT0_X = [WORLD_INT_X_JITTER * random() + -1.0 + (i / WORLD_INT_LINE_COUNT) * 2.0 for i in range(INTX_POINT_COUNT)]
#INT0_Y = [WORLD_INT_Y_JITTER * random() + -0.2 for i in range(INTX_POINT_COUNT)]
#INT_X = [INT0_X]
#INT_Y = [INT0_Y]
#WORLD_LINE_COUNT = len(INT_X[0]) - 1

# World 2
WORLD_LINE_COUNT = 1024
WORLD_INT_X_JITTER = 0.0
WORLD_INT_Y_JITTER = 0.01

INTX_LINE_COUNT = WORLD_LINE_COUNT // 2
INTX_POINT_COUNT = INTX_LINE_COUNT + 1
INT0_X = [WORLD_INT_X_JITTER * random() - 2.0 + (i / INTX_LINE_COUNT) * 4.0 for i in range(INTX_POINT_COUNT)]
INT0_Y = [WORLD_INT_Y_JITTER * random() + 0.2 for i in range(INTX_POINT_COUNT)]
INT0_IOR_I = [1.0] * INTX_LINE_COUNT
INT0_IOR_T = [1.4] * INTX_LINE_COUNT
INT1_X = [WORLD_INT_X_JITTER * random() - 2.0 + (i / INTX_LINE_COUNT) * 4.0 for i in range(INTX_POINT_COUNT)]
INT1_Y = [WORLD_INT_Y_JITTER * random() - 0.2 for i in range(INTX_POINT_COUNT)]
INT1_IOR_I = [1.4] * INTX_LINE_COUNT
INT1_IOR_T = [1.0] * INTX_LINE_COUNT

INT_X = [INT0_X, INT1_X]
INT_Y = [INT0_Y, INT1_Y]
INT_IOR_I = [INT0_IOR_I, INT1_IOR_I]
INT_IOR_T = [INT0_IOR_T, INT1_IOR_T]
